// <auto-generated />
using System;
using Infrastructure.RealDatabase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(MySqlDB))]
    [Migration("20231204154621_UnitOfWork")]
    partial class UnitOfWork
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Domain.Models.Dog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Dogs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10e381fe-4f67-4252-8616-f4add9c979fb"),
                            Name = "Boss"
                        },
                        new
                        {
                            Id = new Guid("0ec31046-0cd6-4c9b-b8c9-129320dc6485"),
                            Name = "Luffsen"
                        },
                        new
                        {
                            Id = new Guid("fe2b9459-8c60-4454-b9f0-7adf70e447d0"),
                            Name = "Pim"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
