// <auto-generated />
using System;
using Infrastructure.RealDatabase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(MySqlDB))]
    [Migration("20231201151217_SeedDataDog")]
    partial class SeedDataDog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Domain.Models.Dog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Dogs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3ef1cf93-7750-450a-ba97-02e6c9642a5c"),
                            Name = "Boss"
                        },
                        new
                        {
                            Id = new Guid("6d34d3cb-7b97-4cd3-9229-79866f06fa6e"),
                            Name = "Luffsen"
                        },
                        new
                        {
                            Id = new Guid("93eec0b5-9b59-4923-89ef-3234abe2e0f9"),
                            Name = "Pim"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
