// <auto-generated />
using System;
using Infrastructure.RealDatabase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(MySqlDB))]
    [Migration("20231213141136_Initialcreate")]
    partial class Initialcreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.Bird", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("CanFly")
                        .HasColumnType("bit");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Birds");

                    b.HasData(
                        new
                        {
                            Id = new Guid("45a3614d-c01a-4459-877f-2d0f7e957474"),
                            CanFly = true,
                            Color = "Blue",
                            Name = "Peppe"
                        },
                        new
                        {
                            Id = new Guid("e8875b12-0630-4914-bcec-eb23a1cfb955"),
                            CanFly = true,
                            Color = "Yellow",
                            Name = "Charlie"
                        },
                        new
                        {
                            Id = new Guid("db514d81-ab5e-4501-9d1d-8cf3fc478ec1"),
                            CanFly = false,
                            Color = "Green",
                            Name = "Kiwi"
                        });
                });

            modelBuilder.Entity("Domain.Models.Cat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LikesToPlay")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Cats");

                    b.HasData(
                        new
                        {
                            Id = new Guid("abf7d09f-42d5-466f-adb6-fdb79cced91d"),
                            Breed = "British Shorthair",
                            LikesToPlay = true,
                            Name = "Kajsa",
                            Weight = 4
                        },
                        new
                        {
                            Id = new Guid("0293b60e-0eb4-414b-a362-829338a1427b"),
                            Breed = "Maine Coon",
                            LikesToPlay = true,
                            Name = "Sigge",
                            Weight = 10
                        },
                        new
                        {
                            Id = new Guid("58749c2d-3655-40a1-a93f-547ef1a0a1c5"),
                            Breed = "Ragdoll",
                            LikesToPlay = true,
                            Name = "Lisa",
                            Weight = 8
                        });
                });

            modelBuilder.Entity("Domain.Models.Dog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Dogs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("709f6285-e943-4d02-a1e3-a4f48088c39b"),
                            Breed = "English Bulldog",
                            Name = "Boss",
                            Weight = 30
                        },
                        new
                        {
                            Id = new Guid("39f670c9-b461-4c2c-8d2d-076bed02a58d"),
                            Breed = "Bernese Mountain Dog",
                            Name = "Luffsen",
                            Weight = 60
                        },
                        new
                        {
                            Id = new Guid("1239796c-9907-40a9-b5cb-397617c5d4a3"),
                            Breed = "Cocker Spaniel",
                            Name = "Pim",
                            Weight = 15
                        });
                });

            modelBuilder.Entity("Domain.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("611c82b3-50ee-4f58-a74d-c6a6f5d9f9f3"),
                            Password = "admin",
                            UserName = "admin"
                        },
                        new
                        {
                            Id = new Guid("e0e7ddcf-55d2-458c-9b6d-7703aca30d8a"),
                            Password = "string",
                            UserName = "string"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
